# Generated by Django 5.2.6 on 2025-09-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_id_alter_learning_id_alter_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
