# Generated by Django 5.2.6 on 2025-09-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpayment',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
