# Generated by Django 4.2 on 2025-09-18 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_manualpayment_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpayment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
