# Generated by Django 4.2 on 2025-09-19 13:14

import courses.models.course
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_couponcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponcode',
            options={'verbose_name': 'Coupon Code', 'verbose_name_plural': 'Coupon Codes'},
        ),
        migrations.RemoveField(
            model_name='couponcode',
            name='discount',
        ),
        migrations.AddField(
            model_name='couponcode',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='discount_value',
            field=models.IntegerField(default=0, help_text='Percentage (0-100) or Fixed amount'),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='max_uses',
            field=models.IntegerField(default=1, help_text='Maximum number of times this coupon can be used'),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='used_count',
            field=models.IntegerField(default=0, help_text='Number of times this coupon has been used'),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='valid_to',
            field=models.DateTimeField(default=courses.models.course.one_year_from_now),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied from coupon', max_digits=10),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='coupon_used',
            field=models.ForeignKey(blank=True, help_text='Coupon used for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.couponcode'),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before coupon discount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
